Feature/#1공기질데이터출력화면
KW-TwoParkHanJungLim/Back-End pull request #11
Opened 2023-01-04 13:44 UTC by Icln

## 구현내용
* 그래프 화면에서 넘겨줄 공기질 데이터 api구현
## api주소
| 주소 | 메서드 |
| --- | --- |
| `/graph` | `POST` |

## Request
```json
{
   "collection":"axr-xxx", //로그인한 id
   "logTime":"2022-11-18", //선택한 날짜
   "sensors":["11111","99999"], //선택한 센서 아이디 리스트(s_id)
   "airData":"temp" //선택한 공기질 종류
}
```
## Response
* 성공 : status(200)
* 실패 : status(500) / Custom(1001)
```json
{
    "sensorData": [
        {
            "s_id": "xxxxx", //센서 아이디
            "temp": 15.77, //선택한 공기질 종류
            "logtime": "2022-11-18T07:32:00.000Z" //선택한 날짜
        },
        {
            "s_id": "xxxxx",
            "temp": 16.99,
            "logtime": "2022-11-18T07:32:00.000Z"
        }
    ]
}
```
## 구현내용
* 그래프 화면에서 넘겨줄 센서 정
## api주소
| 주소 | 메서드 |
| --- | --- |
| `/graph?userId=***` | `GET` |
## Response
* 성공 : status(200)
* 실패 : status(500) / Custom(1000) / Custom(1001)
```json
[
    {
        "sensorName": "센서명",
        "logtime": "측정시간",
        "airData": {
            "temp": "온도",
            "humi": "습도",
            "co2": "이산화탄소",
            "tvoc": "휘발성유기화합물",
            "pm01": "초미세먼지",
            "pm25": "미세먼지",
            "pm10": "미세먼지"
        }
    },
    {
        "sensorName": "",
        "logtime": "",
        "airData": {
            "temp": ,
            "humi": ,
            "co2": ,
            "tvoc": ,
            "pm01": ,
            "pm25": ,
            "pm10": 
        }
    },
]
```

2023-01-05 12:22 UTC, jiione commented on src/main/resources/application.properties
> +server.port=8080
데이터베이스 정보가 깃허브에 올라오는건 위험한거 같습니다. 삭제하고 로그에서도 삭제하는게 좋을거 같습니다.

2023-01-05 19:02 UTC, JinSeoHan reviewed
리뷰 확인 부탁드립니다!

2023-01-05 19:02 UTC, JinSeoHan commented on src/main/java/com/awexomeray/TwoParkHanJungLim/controller/GraphController.java
> +    @PostMapping()
괄호 빼도 될 것 같습니다!

2023-01-05 19:02 UTC, JinSeoHan commented on src/main/java/com/awexomeray/TwoParkHanJungLim/controller/GraphController.java
> +        return ResponseEntity.ok().body(graphAirData);
<img width="849" alt="image" src="https://user-images.githubusercontent.com/87526189/210857761-c671edde-f738-467b-b530-f1e21ea0a194.png">

제가 Map List 타입으로 ResponseEntity에 담아 출력한 테스트 결과 입니다.
<img width="512" alt="image" src="https://user-images.githubusercontent.com/87526189/210859211-a6c476dd-e537-4f1c-a526-c6939eb06c59.png">
수정 시 해당사진의 sensorData부분 없이 깔끔하게 출력할 수 있을 것 같습니다!

아래의 사진은 제가 출력한 결과 예시입니다.
<img width="545" alt="image" src="https://user-images.githubusercontent.com/87526189/210859787-81657083-864c-46d4-ae2f-5d5b61782af3.png">

2023-01-06 01:29 UTC, Icln commented on src/main/java/com/awexomeray/TwoParkHanJungLim/controller/GraphController.java
> +    @PostMapping()
확인했습니다!

2023-01-06 01:35 UTC, Icln commented on src/main/java/com/awexomeray/TwoParkHanJungLim/controller/GraphController.java
> +        return ResponseEntity.ok().body(graphAirData);
확인했습니다!

2023-01-06 01:43 UTC, Icln commented on src/main/java/com/awexomeray/TwoParkHanJungLim/controller/GraphController.java
> +        return ResponseEntity.ok().body(graphAirData);
변경했는데 확인 부탁드립니다!

2023-01-07 09:00 UTC, jiione approved these changes
LGTM~

2023-01-10 07:19 UTC, JinSeoHan approved these changes
LGTM

2023-01-10 07:34 UTC, jiione requested changes

2023-01-10 07:34 UTC, jiione commented on src/main/java/com/awexomeray/TwoParkHanJungLim/dao/AirDataDao.java
> +        //mongoTemplate.indexOps(requestGraphDataDto.getCollection());
필요하지 않는 주석은 지워주시길 바랍니다.

2023-01-10 07:36 UTC, Icln commented on src/main/java/com/awexomeray/TwoParkHanJungLim/dao/AirDataDao.java
> +        //mongoTemplate.indexOps(requestGraphDataDto.getCollection());
수정했습니다.

2023-01-10 07:40 UTC, jiione approved these changes
LGTM~~

2023-01-10 07:41 UTC, merged